apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lvillanetti
  title: Luiz Villanetti
spec:
  profile:
    displayName: Luiz Villanetti
    email: lvillanetti@uoledtech.com
  memberOf:
  - group:sales
