apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rsilva6
  title: Robson Silva
spec:
  profile:
    displayName: Robson Silva
    email: rsilva6@uoledtech.com
  memberOf:
  - group:acquisition
