apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bsd_amarques
  title: Ailton Tadeu Marques
  description: UX
  annotations:
    uoledtech.org/email: bsd_amarques+edtech@uoledtech.com
  tags:
    - squad-sales-success
spec:
  profile:
    displayName: Ailton Tadeu Marques
    email: bsd_amarques+edtech@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf:
    - squad-sales-success
