apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lalcantara
  title: Lucas Pedro
  description: PM
  annotations:
    uoledtech.org/email: lalcantara+edtech@uoledtech.com
  tags:
    - squad-sales-success
spec:
  profile:
    displayName: Lucas Pedro
    email: lalcantara+edtech@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf:
    - squad-sales-success
