apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rodfigueired
  title: Rodrigo Martins Figueiredo
  description: DEV
  annotations:
    uoledtech.org/email: rodfigueired+edtech@uoledtech.com
  tags:
    - squad-sales-success
spec:
  profile:
    displayName: Rodrigo Martins Figueiredo
    email: rodfigueired+edtech@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf:
    - squad-sales-success
