apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rvaranda
  title: Rodrigo Victor Varanda
  description: TTL
  annotations:
    uoledtech.org/email: rvaranda+edtech@uoledtech.com
  tags:
    - tribo-core
spec:
  profile:
    displayName: Rodrigo Victor Varanda
    email: rvaranda+edtech@uoledtech.com
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf:
    - tribo-core
