apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: back-gerador-cert-hub-prod
  tags:
  - academic
  - certificates
  - nodejs
  - typescript
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/gerador-certificados-backend
    github.com/project-slug: uoledtech-opm/gerador-certificados-backend
    datadog.com/apm-url: https://opm.datadoghq.com/apm/entity/service%3Aback-gerador-cert-hub-prod?env=hub-production
    datadog.com/logs-url: https://opm.datadoghq.com/logs?query=env%3Ahub-production%20service%3Aback-gerador-cert-hub-prod
    database.types: MySQL
    database.orm: Mongoose
    sqs.queues: sqs-consumer,sqs-producer
  title: Back Gerador Cert Hub Prod
  description: Serviço de gestão de certificados. Gera e gerencia certificados de
    conclusão.
  links:
    - url: https://github.com/uoledtech-opm/gerador-certificados-backend
      title: GitHub Repository
      icon: github
    - url: https://opm.datadoghq.com/apm/entity/service%3Aback-gerador-cert-hub-prod?env=hub-production
      title: Datadog APM
      icon: monitoring
    - url: https://opm.datadoghq.com/logs?query=env%3Ahub-production%20service%3Aback-gerador-cert-hub-prod
      title: Datadog Logs
      icon: monitoring
spec:
  type: backend
  lifecycle: production
  owner: group:acquisition
  system: opm-production
  dependsOn:
  - resource:sqs-consumer
  - resource:sqs-producer
  - resource:database-gerador_cert_hub_prod-mysql
