apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: back-ie-analytics-int
  tags:
  - analytics
  - data-integration
  - nodejs
  - typescript
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/analytics-integration-ie-backend
    github.com/project-slug: uoledtech-opm/analytics-integration-ie-backend
    datadog.com/apm-url: https://opm.datadoghq.com/apm/entity/service%3Aback-ie-analytics-int?env=pucrs-grad-production
    datadog.com/logs-url: https://opm.datadoghq.com/logs?query=env%3Apucrs-grad-production%20service%3Aback-ie-analytics-int
  title: Back Ie Analytics Int
  description: Serviço de analytics. Coleta e processa dados analíticos.
spec:
  type: backend
  lifecycle: production
  owner: todo-owner
  system: opm-production
