apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: back-hub-bff-sales
  tags:
  - api-gateway
  - bff
  - nestjs
  - nodejs
  - sales
  - typescript
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/bff-sales-hub-vendas-backend
    github.com/project-slug: uoledtech-opm/bff-sales-hub-vendas-backend
    datadog.com/apm-url: https://opm.datadoghq.com/apm/entity/service%3Aback-hub-bff-sales?env=hub-production
    datadog.com/logs-url: https://opm.datadoghq.com/logs?query=env%3Ahub-production%20service%3Aback-hub-bff-sales
    sqs.queues: sqs-hubspot-create-contact-deal-hub
  title: Back Hub Bff Sales
  description: Backend For Frontend (BFF) para o sistema de vendas. Orquestra chamadas
    para múltiplos serviços backend e fornece uma API unificada para o frontend.
  links:
    - url: https://github.com/uoledtech-opm/bff-sales-hub-vendas-backend
      title: GitHub Repository
      icon: github
    - url: https://opm.datadoghq.com/apm/entity/service%3Aback-hub-bff-sales?env=hub-production
      title: Datadog APM
      icon: monitoring
    - url: https://opm.datadoghq.com/logs?query=env%3Ahub-production%20service%3Aback-hub-bff-sales
      title: Datadog Logs
      icon: monitoring
spec:
  type: backend
  lifecycle: production
  owner: group:sales
  system: checkout-onepage
  dependsOn:
  - component:back-feature-flag-hub-prod
  - component:back-hub-cep-vendas
  - component:back-hub-clientes
  - component:back-hub-gtw-pagamento
  - component:back-hub-integration
  - component:back-hub-pagamentos
  - component:back-hub-pedidos
  - component:back-hub-precificacao
  - component:back-hub-promocao
  - component:back-processo-seletivo-hub-prod
  - component:back-produtos-hub-prod
  - resource:sqs-hubspot-create-contact-deal-hub
