apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: back-hub-worker
  tags:
  - background-jobs
  - nodejs
  - platform
  - typescript
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/worker-hub-vendas-backend
    github.com/project-slug: uoledtech-opm/worker-hub-vendas-backend
    datadog.com/apm-url: https://opm.datadoghq.com/apm/entity/service%3Aback-hub-worker?env=hub-production
    datadog.com/logs-url: https://opm.datadoghq.com/logs?query=env%3Ahub-production%20service%3Aback-hub-worker
    sqs.queues: sqs-webhook-vendas
  title: Back Hub Worker
  description: Worker para processamento assíncrono. Processa tarefas em background.
  links:
    - url: https://github.com/uoledtech-opm/worker-hub-vendas-backend
      title: GitHub Repository
      icon: github
    - url: https://opm.datadoghq.com/apm/entity/service%3Aback-hub-worker?env=hub-production
      title: Datadog APM
      icon: monitoring
    - url: https://opm.datadoghq.com/logs?query=env%3Ahub-production%20service%3Aback-hub-worker
      title: Datadog Logs
      icon: monitoring
spec:
  type: backend
  lifecycle: production
  owner: group:sales
  system: opm-production
  dependsOn:
  - component:back-hub-clientes
  - component:back-hub-pagamentos
  - component:back-hub-pedidos
  - component:back-produtos-hub-prod
  - resource:sqs-webhook-vendas
  - resource:sqs-webhook-vendas
