apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: back-hub-gtw-pagamento
  tags:
  - nodejs
  - payments
  - sales
  - typescript
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/gateway-pagamento-hub-vendas-backend
    github.com/project-slug: uoledtech-opm/gateway-pagamento-hub-vendas-backend
    datadog.com/apm-url: https://opm.datadoghq.com/apm/entity/service%3Aback-hub-gtw-pagamento?env=hub-production
    datadog.com/logs-url: https://opm.datadoghq.com/logs?query=env%3Ahub-production%20service%3Aback-hub-gtw-pagamento
    sqs.queues: sqs-adyen-checkout-notify-hub,sqs-adyen-checkout-notify-tkt-hub,sqs-adyen-installment-payment-settlement-fia-hub,sqs-adyen-installment-payment-settlement-hub,sqs-adyen-installment-payment-settlement-pucrs-hub,sqs-adyen-send-billing-hub,sqs-checkout-financial-goexplosion-hub,sqs-hubspot-create-contact-deal-hub,sqs-send-data-matrix-fia-hub,sqs-send-data-matrix-hub,sqs-send-data-matrix-pucrs-hub,sqs-send-data-matrix-unesc-hub
  title: Back Hub Gtw Pagamento
  description: Gateway de pagamento. Orquestra processamento de pagamentos com múltiplos
    provedores.
  links:
    - url: https://github.com/uoledtech-opm/gateway-pagamento-hub-vendas-backend
      title: GitHub Repository
      icon: github
    - url: https://opm.datadoghq.com/apm/entity/service%3Aback-hub-gtw-pagamento?env=hub-production
      title: Datadog APM
      icon: monitoring
    - url: https://opm.datadoghq.com/logs?query=env%3Ahub-production%20service%3Aback-hub-gtw-pagamento
      title: Datadog Logs
      icon: monitoring
spec:
  type: backend
  lifecycle: production
  owner: group:sales
  system: checkout-campus
  dependsOn:
  - component:back-feature-flag-hub-prod
  - component:back-hub-clientes
  - component:back-hub-integration
  - component:back-hub-pagamentos
  - component:back-hub-pedidos
  - component:back-hub-promocao
  - component:back-produtos-hub-prod
  - resource:sqs-adyen-checkout-notify-hub
  - resource:sqs-adyen-checkout-notify-tkt-hub
  - resource:sqs-adyen-installment-payment-settlement-fia-hub
  - resource:sqs-adyen-installment-payment-settlement-hub
  - resource:sqs-adyen-installment-payment-settlement-pucrs-hub
  - resource:sqs-adyen-send-billing-hub
  - resource:sqs-checkout-financial-goexplosion-hub
  - resource:sqs-hubspot-create-contact-deal-hub
  - resource:sqs-send-data-matrix-fia-hub
  - resource:sqs-send-data-matrix-hub
  - resource:sqs-send-data-matrix-pucrs-hub
  - resource:sqs-send-data-matrix-unesc-hub
  - resource:sqs-adyen-checkout-notify-hub
  - resource:sqs-adyen-checkout-notify-tkt-hub
  - resource:sqs-adyen-installment-payment-settlement-fia-hub
  - resource:sqs-adyen-installment-payment-settlement-hub
  - resource:sqs-adyen-installment-payment-settlement-pucrs-hub
  - resource:sqs-adyen-send-billing-hub
  - resource:sqs-checkout-financial-goexplosion-hub
  - resource:sqs-hubspot-create-contact-deal-hub
  - resource:sqs-send-data-matrix-fia-hub
  - resource:sqs-send-data-matrix-hub
  - resource:sqs-send-data-matrix-pucrs-hub
  - resource:sqs-send-data-matrix-unesc-hub
