apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: back-interacao-aluno-pucrs
  tags:
  - academic
  - ava
  - nodejs
  - students
  - typescript
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/interacao-aluno-ie-backend
    github.com/project-slug: uoledtech-opm/interacao-aluno-ie-backend
    datadog.com/apm-url: https://opm.datadoghq.com/apm/entity/service%3Aback-interacao-aluno-pucrs?env=pucrs-grad-production
    datadog.com/logs-url: https://opm.datadoghq.com/logs?query=env%3Apucrs-grad-production%20service%3Aback-interacao-aluno-pucrs
    database.types: MySQL
    database.orm: TypeORM
  title: Back Interacao Aluno Pucrs
  description: Serviço de interação com alunos. Gerencia interações e atividades de
    alunos.
spec:
  type: backend
  lifecycle: production
  owner: group:ava
  system: opm-production
  dependsOn:
  - resource:database-${DB_NAME}-mysql
