apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chatai-frontend
  tags:
  - ai-chat
  - frontend
  - javascript
  - react
  - sales
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/chatai-frontend
    github.com/project-slug: uoledtech-opm/chatai-frontend
  title: Chatai Frontend
  description: Aplicação frontend para interface de usuário.
  links:
    - url: https://github.com/uoledtech-opm/chatai-frontend
      title: GitHub Repository
      icon: github
spec:
  type: frontend
  lifecycle: production
  owner: group:sales
  system: opm-production
