apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecommerce-veiculos-shared
  title: E-commerce Veículos - Shared Library
  description: Biblioteca compartilhada com tipos TypeScript, utilitários e funções comuns
  tags: [library, typescript, shared, utils]
  annotations:
    github.com/project-slug: emingues-xx/ecommerce-veiculos-shared
    backstage.io/source-location: url:https://github.com/emingues-xx/ecommerce-veiculos-shared
spec:
  type: library
  lifecycle: production
  owner: tribe-ecommerce
  system: ecommerce-veiculos
  techdocs:
    builder: mkdocs
    generator: techdocs
    publisher:
      type: local
      target: ./docs/components/ecommerce-veiculos-shared