apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecommerce-veiculos-pipelines
  title: E-commerce Veículos - CI/CD Pipelines & Automation
  description: Workflows de CI/CD e automação inteligente de documentação usando Claude API
  tags: [devops, cicd, pipelines, automation, documentation, claude-api]
  annotations:
    github.com/project-slug: emingues-xx/ecommerce-veiculos-pipelines
    backstage.io/source-location: url:https://github.com/emingues-xx/ecommerce-veiculos-pipelines
spec:
  type: tool
  lifecycle: production
  owner: tribe-ecommerce
  system: ecommerce-veiculos
  techdocs:
    builder: mkdocs
    generator: techdocs
    publisher:
      type: local
      target: ./docs/components/ecommerce-veiculos-pipelines