apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vitrine-veiculos-bff
  title: Vitrine de Veículos - BFF
  description: Backend for Frontend que otimiza dados da vitrine para o frontend
  tags: [backend, nodejs, bff, vitrine]
  annotations:
    github.com/project-slug: emingues-xx/vitrine-veiculos-bff
spec:
  type: service
  lifecycle: production
  owner: squad-vitrine
  system: vitrine-veiculos
  providesApis:
    - vitrine-veiculos-bff-api
  consumesApis:
    - vitrine-veiculos-api
  dependsOn:
    - component:vitrine-veiculos-api
    - component:ecommerce-veiculos-shared