apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: database-cn-hub-controle-funcionario-mysql
  title: Database CN Hub Controle Funcionario MySQL
  description: |
    | Database | Tipo | Ambiente |
    | ------   | ---- | -------- |
    | CN_HUB_ControleFuncionario | MySQL | Production |
    
    Banco de dados MySQL para controle de funcionários do hub administrativo EAD.
  tags:
  - database
  - mysql
  - funcionario
  - employee
  - hub-prod
  - academic
  annotations:
    database.type: MySQL
spec:
  type: database
  lifecycle: production
  owner: group:ava
  system: opm-production
