apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: squad-aquisicao
  description: squad-aquisicao
spec:
  type: team
  profile:
    email: l-uoledtech-aquisicao-opm@uolinc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: tribo-growth
  children: [tribo-growth]
