apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-gateway-pagamento
  title: API Gateway Pagamento
  description: API do gateway de pagamento. Orquestra processamento de pagamentos com múltiplos provedores.
  tags:
  - gateway
  - pagamento
  - payments
  - nestjs
  - rest
  links:
    - url: https://back-hub-gtw-pagamento-dev.edtech.com.br
      title: URI Develop
      icon: code
    - url: https://back-gtw-pagamento-hmg.edtech.com.br
      title: URI Homolog
      icon: code
    - url: https://back-hub-gtw-pagamento-dev.edtech.com.br/api/docs
      title: Swagger Develop
      icon: code
    - url: https://github.com/uoledtech-opm/gateway-pagamento-hub-vendas-backend
      title: GitHub Repo
      icon: github
    - url: https://opm.datadoghq.com/apm/entity/service%3Aback-hub-gtw-pagamento?env=hub-production
      title: Datadog APM
      icon: monitoring
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/gateway-pagamento-hub-vendas-backend
    github.com/project-slug: uoledtech-opm/gateway-pagamento-hub-vendas-backend
spec:
  type: rest
  lifecycle: production
  owner: group:sales
  system: opm-production
  definition:
    $text: https://back-hub-gtw-pagamento-dev.edtech.com.br/api/docs-json
