apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-ie-autenticacao
  title: API Ie Autenticacao
  description: Serviço de autenticação. Gerencia login e sessões de usuários.
  tags:
  - academic
  - authentication
  - security
  links:
  - url: https://back-ie-autenticacao-dev.edtech.com.br
    title: URI Develop
    icon: code
  - url: https://back-ie-autenticacao-hmg.edtech.com.br
    title: URI Homolog
    icon: code
  - url: https://back-ie-autenticacao-dev.edtech.com.br/api/docs
    title: Swagger Develop
    icon: code
  - url: https://github.com/uoledtech-opm/autenticacao-ie-backend
    title: GitHub Repo
    icon: github
  - url: https://opm.datadoghq.com/apm/entity/service%3Aback-ie-autenticacao?env=pucrs-grad-production
    title: Datadog APM
    icon: monitoring
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/autenticacao-ie-backend
    github.com/project-slug: uoledtech-opm/autenticacao-ie-backend
spec:
  type: rest
  lifecycle: production
  owner: group:academico
  system: opm-production
  definition:
    $text: https://back-ie-autenticacao-dev.edtech.com.br/api/docs-json
