apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-precificacao
  title: API Precificação
  description: API do serviço de precificação de produtos e cursos. Calcula valores, descontos e opções de parcelamento.
  tags:
  - precificacao
  - pricing
  - nestjs
  - rest
  - sales
  links:
    - url: https://back-hub-precificacao-dev.edtech.com.br
      title: URI Develop
      icon: code
    - url: https://back-precificacao-hmg.edtech.com.br
      title: URI Homolog
      icon: code
    - url: https://back-hub-precificacao-dev.edtech.com.br/api/docs
      title: Swagger Develop
      icon: code
    - url: https://github.com/uoledtech-opm/precificacao-hub-vendas-backend
      title: GitHub Repo
      icon: github
    - url: https://opm.datadoghq.com/apm/entity/service%3Aback-hub-precificacao?env=hub-production
      title: Datadog APM
      icon: monitoring
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/precificacao-hub-vendas-backend
    github.com/project-slug: uoledtech-opm/precificacao-hub-vendas-backend
spec:
  type: rest
  lifecycle: production
  owner: group:sales
  system: opm-production
  definition:
    $text: https://back-hub-precificacao-dev.edtech.com.br/api/docs-json
