apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-webhook
  title: API Webhook
  description: API do serviço de webhooks. Recebe e processa notificações de sistemas externos.
  tags:
  - webhook
  - integrations
  - nestjs
  - rest
  links:
    - url: https://back-hub-webhook-dev.edtech.com.br
      title: URI Develop
      icon: code
    - url: https://back-webhook-hmg.edtech.com.br
      title: URI Homolog
      icon: code
    - url: https://back-hub-webhook-dev.edtech.com.br/api/docs
      title: Swagger Develop
      icon: code
    - url: https://github.com/uoledtech-opm/webhook-opm-hub-vendas-backend
      title: GitHub Repo
      icon: github
    - url: https://opm.datadoghq.com/apm/entity/service%3Aback-webhook-hub-prod?env=hub-production
      title: Datadog APM
      icon: monitoring
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/webhook-opm-hub-vendas-backend
    github.com/project-slug: uoledtech-opm/webhook-opm-hub-vendas-backend
spec:
  type: rest
  lifecycle: production
  owner: group:payops
  system: opm-production
  definition:
    $text: https://back-hub-webhook-dev.edtech.com.br/api/docs-json
