apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-vendas-bff
  title: API Vendas Bff Hub Prod
  description: Serviço backend para processamento de requisições e lógica de negócio.
  tags:
  - api-gateway
  - bff
  - nestjs
  - sales
  links:
  - url: https://back-vendas-bff-dev.edtech.com.br
    title: URI Develop
    icon: code
  - url: https://back-vendas-bff-hmg.edtech.com.br
    title: URI Homolog
    icon: code
  - url: https://back-vendas-bff-dev.edtech.com.br/api/docs
    title: Swagger Develop
    icon: code
  - url: https://github.com/uoledtech-opm/bff-vendas-hub-vendas-backend
    title: GitHub Repo
    icon: github
  - url: https://opm.datadoghq.com/apm/entity/service%3Aback-vendas-bff-hub-prod?env=hub-production
    title: Datadog APM
    icon: monitoring
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/bff-vendas-hub-vendas-backend
    github.com/project-slug: uoledtech-opm/bff-vendas-hub-vendas-backend
spec:
  type: rest
  lifecycle: production
  owner: group:sales
  system: opm-production
  definition:
    $text: https://back-vendas-bff-dev.edtech.com.br/api/docs-json
