apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-ie-dash-vendas
  title: API Ie Dash Vendas Prod
  description: Dashboard de vendas. Fornece relatórios e métricas de vendas para gestão.
  tags:
  - analytics
  - dashboard
  - sales
  - sales-analytics
  links:
  - url: https://back-ie-dash-vendas-dev.edtech.com.br
    title: URI Develop
    icon: code
  - url: https://back-ie-dash-vendas-hmg.edtech.com.br
    title: URI Homolog
    icon: code
  - url: https://back-ie-dash-vendas-dev.edtech.com.br/api/docs
    title: Swagger Develop
    icon: code
  - url: https://github.com/uoledtech-opm/dashboard-vendas-ie-backend
    title: GitHub Repo
    icon: github
  - url: https://opm.datadoghq.com/apm/entity/service%3Aback--dash-vendas-uninassau?env=ie-production
    title: Datadog APM
    icon: monitoring
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/dashboard-vendas-ie-backend
    github.com/project-slug: uoledtech-opm/dashboard-vendas-ie-backend
spec:
  type: rest
  lifecycle: production
  owner: group:payops
  system: opm-production
  definition:
    $text: https://back-ie-dash-vendas-dev.edtech.com.br/api/docs-json
