apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-autorizacao-pucrs
  title: API Autorizacao Pucrs
  description: Serviço de autorização e permissões. Gerencia acesso e permissões de
    usuários.
  tags:
  - academic
  - authentication
  - security
  links:
  - url: https://back-autorizacao-pucrs-dev.edtech.com.br
    title: URI Develop
    icon: code
  - url: https://back-autorizacao-pucrs-hmg.edtech.com.br
    title: URI Homolog
    icon: code
  - url: https://back-autorizacao-pucrs-dev.edtech.com.br/api/docs
    title: Swagger Develop
    icon: code
  - url: https://github.com/uoledtech-opm/autorizacao-ie-backend
    title: GitHub Repo
    icon: github
  - url: https://opm.datadoghq.com/apm/entity/service%3Aback-autorizacao-pucrs?env=pucrs-grad-production
    title: Datadog APM
    icon: monitoring
  annotations:
    backstage.io/source-location: url:https://github.com/uoledtech-opm/autorizacao-ie-backend
    github.com/project-slug: uoledtech-opm/autorizacao-ie-backend
spec:
  type: rest
  lifecycle: production
  owner: group:academico
  system: opm-production
  definition:
    $text: https://back-autorizacao-pucrs-dev.edtech.com.br/api/docs-json
