apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backoffice-veiculos-bff-api
  title: Backoffice de Veículos BFF API
  description: Backend for Frontend API para painel administrativo
  tags: [api, bff, admin, dashboard]
spec:
  type: openapi
  lifecycle: production
  owner: squad-backoffice
  system: backoffice-veiculos
  definition: |
    openapi: 3.0.3
    info:
      title: Backoffice de Veículos BFF API
      version: 1.0.0
      description: API otimizada para frontend administrativo
    paths:
      /api/dashboard:
        get:
          summary: Dados do dashboard
          security:
            - bearerAuth: []
          responses:
            '200':
              description: Métricas do dashboard retornadas