apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: opm-components
  description: Componentes do catálogo de OPM
spec:
  type: url
  targets:
    - ./components/back--dash-vendas-uninassau.yaml
    - ./components/back-autorizacao-pucrs.yaml
    - ./components/back-backoffice-hub-prod.yaml
    - ./components/back-categorias-hub-prod.yaml
    - ./components/back-cert-bff-hub-prod.yaml
    - ./components/back-comunicacao-pucrs.yaml
    - ./components/back-conteudo-pucrs.yaml
    - ./components/back-dash-alunos-pucrs.yaml
    - ./components/back-dash-alunos-uninassau.yaml
    - ./components/back-dash-cursos-pucrs.yaml
    - ./components/back-dash-cursos-uninassau.yaml
    - ./components/back-dash-disciplinas-pucrs.yaml
    - ./components/back-dash-disciplinas-uninassau.yaml
    - ./components/back-dash-financeiro-pucrs.yaml
    - ./components/back-dash-financeiro-uninassau.yaml
    - ./components/back-dash-vendas-pucrs.yaml
    - ./components/back-envia-email-hub-pd.yaml
    - ./components/back-envia-email-hub-prod.yaml
    - ./components/back-feature-flag-hub-prod.yaml
    - ./components/back-gerador-cert-hub-prod.yaml
    - ./components/back-hub-backoffice-pd.yaml
    - ./components/back-hub-bff-sales.yaml
    - ./components/back-hub-cep-vendas.yaml
    - ./components/back-hub-cert-bff-pd.yaml
    - ./components/back-hub-chat-ai.yaml
    - ./components/back-hub-chatai-prod.yaml
    - ./components/back-hub-clientes.yaml
    - ./components/back-hub-conteudo.yaml
    - ./components/back-hub-contratos.yaml
    - ./components/back-hub-cursos.yaml
    - ./components/back-hub-gerador-cert-pd.yaml
    - ./components/back-hub-gtw-pagamento.yaml
    - ./components/back-hub-integration.yaml
    - ./components/back-hub-matricula.yaml
    - ./components/back-hub-pagamentos.yaml
    - ./components/back-hub-pedidos.yaml
    - ./components/back-hub-precificacao.yaml
    - ./components/back-hub-promocao.yaml
    - ./components/back-hub-recommender.yaml
    - ./components/back-hub-templates-pd.yaml
    - ./components/back-hub-twilio-hubspot.yaml
    - ./components/back-hub-worker.yaml
    - ./components/back-ie-alunos.yaml
    - ./components/back-ie-analytics-int.yaml
    - ./components/back-ie-autenticacao.yaml
    - ./components/back-ie-avaliacao.yaml
    - ./components/back-ie-callback.yaml
    - ./components/back-ie-cognito.yaml
    - ./components/back-ie-conteudo-prod.yaml
    - ./components/back-ie-cursos.yaml
    - ./components/back-ie-dash-alunos-faap.yaml
    - ./components/back-ie-dash-cursos-faap.yaml
    - ./components/back-ie-dash-disci-faap.yaml
    - ./components/back-ie-dash-finance-faap.yaml
    - ./components/back-ie-dash-financeiro-prod.yaml
    - ./components/back-ie-dash-vendas-faap.yaml
    - ./components/back-ie-dash-vendas-prod.yaml
    - ./components/back-ie-data-integration.yaml
    - ./components/back-ie-ead-bff.yaml
    - ./components/back-ie-engajamento.yaml
    - ./components/back-ie-federation-dados.yaml
    - ./components/back-ie-hub-indicacoes.yaml
    - ./components/back-ie-mailgun-int-faap.yaml
    - ./components/back-ie-mailgun-integra-scsp.yaml
    - ./components/back-ie-matricula.yaml
    - ./components/back-ie-notas-faap.yaml
    - ./components/back-ie-notas-impacta.yaml
    - ./components/back-ie-notas-scsp.yaml
    - ./components/back-ie-player.yaml
    - ./components/back-ie-progressos.yaml
    - ./components/back-ie-supervisores.yaml
    - ./components/back-instituicao-ensino-hub-prod.yaml
    - ./components/back-integracao-adyen-hub-prod.yaml
    - ./components/back-interacao-aluno-pucrs.yaml
    - ./components/back-linkflow-prod.yaml
    - ./components/back-mailgun-integra-pucrs.yaml
    - ./components/back-mailgun-integration-impacta.yaml
    - ./components/back-mailgun-integration-uninassau.yaml
    - ./components/back-notas-pucrs.yaml
    - ./components/back-notas-uninassau.yaml
    - ./components/back-object-integration-hub-prod.yaml
    - ./components/back-processo-seletivo-hub-prod.yaml
    - ./components/back-produtos-hub-prod.yaml
    - ./components/back-recorrencia-hub-prod.yaml
    - ./components/back-templates-hub-prod.yaml
    - ./components/back-vendas-bff-hub-prod.yaml
    - ./components/back-webhook-hub-prod.yaml
    - ./components/campus-digital-ie-front.yaml
    - ./components/chatai-frontend.yaml
    - ./components/checkout-hub-vendas-frontend.yaml
    - ./components/checkout-onepage-hub-vendas-frontend.yaml
    - ./components/checkout-whitelabel.yaml
    - ./components/professores-ie-frontend.yaml
