apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: opm-domains
  description: Domínios do catálogo de OPM
spec:
  type: url
  targets:
    - ./domains/academic.yaml
    - ./domains/analytics.yaml
    - ./domains/apis-financeiras.yaml
    - ./domains/ava.yaml
    - ./domains/certificates.yaml
    - ./domains/gestao-de-parcelas.yaml
    - ./domains/integrations.yaml
    - ./domains/motor-de-recorrencia.yaml
    - ./domains/pagamentos.yaml
    - ./domains/reconhecimento-de-receita.yaml
    - ./domains/vendas.yaml
